### ISSUE TITLE
No logra hacer el fetch

### ISSUE THREAD

**Issue by LordFritos** [Ctrl-Alt-Tec/Anuario#11]
```Access to fetch at 'https://cors-anywhere.herokuapp.com/ctrl-alt-tec.herokuapp.com/colab/saprepa/anuario/ago2020' from origin 'https://ctrl-alt-tec.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by edvilme** [comment]
Perdòn, ando un poco ocupado esta semana pero lo reviso

**Comment by edvilme** [comment]
Dun
