### ISSUE TITLE
Estructura de datos dummy

### ISSUE THREAD

**Issue by edvilme** [Ctrl-Alt-Tec/Anuario#9]
Crear un archivo json con una simulación del archivo que obtendremos cuando estén todas las respuestas.  Lo tengo esta semana. @edvilme

**Comment by edvilme** [comment]
@LordFritos Los datos los recuperamos de acá
http://ctrl-alt-tec.herokuapp.com/colab/saprepa/anuario

Hoy tengo mucha tarea pero al rato veo cómo hacerle para recuperar las imágenes directamente. Por ahora, espero sirva ;D

**Comment by LordFritos** [comment]
Ok, cómo va a estar la estructura de las propiedades?
